export { default as About} from './AboutPage'
export { default as Auction } from './AuctionPage'
export { default as Contest } from './ContestPage'
export { default as Grant } from './GrantPage'
export { default as Home } from './HomePage'
export { default as Privacy } from './PrivacyPage'
export { default as NotFound } from './HomePage'
export { default as Tender } from './TenderPage'
export { default as Term } from './TermPage'